# SITE CONFIGURATION
title: Parlametria # your site title
author: OKFBR # You :P
description: > # Meta description of Homepage
  Inteligência de dados para ação cidadã
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Open Knowledge Brasil
  links:
    - https://twitter.com/okfnbr
    - https://www.facebook.com/OpenKnowledgeBrasil
    - https://discuss.okfn.org/c/local-groups/okbr


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Projetos', link: '/projetos'}
  - {name: 'Relatórios', link: '/relatórios'}
  - {name: 'Na mídia', link: '/namidia'}
  - {name: 'Sobre', link: '/sobre'}
  - {name: 'Blog', link: '/blog'}

tagline: >
  Inteligência de dados para ação cidadã

hero_img: posts/parlametria_bg.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
email: contato@ok.org.br # email for form submission

twitter_username: okfnbr # replace with your_twitter_username or comment to remove link from footer

# disqus:
  # shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
